services:
  web:
    image: nginx
    ports:
      - 81:80
    restart: always
    volumes:
      - /Users/arina./projects/online-shop1/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /Users/arina./projects/online-shop1/var/www/html
    depends_on:
      - php-fpm
      - postgres

  php-fpm:
    build: ./docker/php
    restart: always
    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 54324:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}